#https://github.com/openzipkin/docker-zipkin/blob/master/docker-compose.yml

version: '3'

services:
  mysql:
    image: mysql:8.0.16
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_USER=demo
      - MYSQL_DATABASE=demo
      - MYSQL_PASSWORD=123123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-mysql-master.sql /docker-entrypoint-initdb.d/init-mysql-master.sql
    ports:
      - 3306:3306
    networks:
      - net

volumes:
  mysql_data:
networks:
  net:
